import nextPlugin from "@next/eslint-plugin-next"
import reactHooks from "eslint-plugin-react-hooks"
import tseslint from "typescript-eslint"

const config = [
  {
    ignores: [
      ".next",
      ".cache",
      "backups",
      // Generated by Next on build.
      "next-env.d.ts",
      // Vendored: copied verbatim from node_modules by
      // scripts/copy-maplibre-assets.mjs, so linting them is pointless and
      // they are minified enough to drown everything else.
      "public/**",
      "src/test-setup.ts",
      "**/*.test.ts",
      "**/*.test.tsx",
      "**/*.spec.ts",
      "**/*.spec.tsx",
    ],
  },
  ...tseslint.configs.recommended,
  reactHooks.configs.flat.recommended,
  {
    rules: {
      // The classic hook rules earn their keep immediately: rules-of-hooks
      // caught a useState called after an early return in TimelineWithMap,
      // which would have thrown the moment a timeline finished loading.
      //
      // v7 also bundles the React Compiler rules. These three flag 13 sites
      // across components that predate the plugin, and several are the
      // legitimate "read client-only state after hydration" pattern that must
      // not be naively removed. Resolving them is a behaviour-affecting
      // refactor rather than a lint config change, so they are tracked in
      // #57 and turned off until then rather than left as standing noise.
      "react-hooks/set-state-in-effect": "off",
      "react-hooks/purity": "off",
      "react-hooks/refs": "off",
    },
  },
  {
    files: ["**/*.{js,jsx,ts,tsx,mjs,mts,cjs,cts}"],
    plugins: {
      "@next/next": nextPlugin,
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
    },
  },
  {
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: {
      parserOptions: {
        project: true,
      },
    },
    rules: {
      "@typescript-eslint/array-type": "off",
      "@typescript-eslint/consistent-type-definitions": ["error", "type"],
      "@typescript-eslint/consistent-type-imports": [
        "warn",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/require-await": "off",
      "@typescript-eslint/no-misused-promises": [
        "error",
        { checksVoidReturn: { attributes: false } },
      ],
      // Enforce nullish coalescing over logical OR when appropriate
      "@typescript-eslint/prefer-nullish-coalescing": "off",
      "@typescript-eslint/prefer-optional-chain": "error",
      // Prevent any types (relaxed for external data handling)
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unsafe-assignment": "warn",
      "@typescript-eslint/no-unsafe-member-access": "warn",
      "@typescript-eslint/no-unsafe-call": "warn",
      "@typescript-eslint/no-unsafe-return": "warn",
      "@typescript-eslint/no-unsafe-argument": "warn",
      // Type inference improvements
      "@typescript-eslint/no-inferrable-types": "error",
      // Prefer function declarations over arrow functions for top-level functions
      "prefer-arrow-callback": "off",
      "func-style": ["error", "declaration", { allowArrowFunctions: true }],
      // No semicolons at end of statements
      semi: ["error", "never"],
    },
  },
  {
    linterOptions: {
      reportUnusedDisableDirectives: true,
    },
  },
]

export default config
