export const denominationOptions = [
  { value: "Denarius", label: "Denarius" },
  { value: "Antoninianus", label: "Antoninianus" },
  { value: "Siliqua", label: "Siliqua" },
  { value: "Sestertius", label: "Sestertius" },
  { value: "Follis", label: "Follis" },
  { value: "Nummus", label: "Nummus" },
  { value: "As", label: "As" },
  { value: "Dupondius", label: "Dupondius" },
  { value: "Tetradrachm", label: "Tetradrachm" },
  { value: "Drachm", label: "Drachm" },
  { value: "Aureus", label: "Aureus" },
  { value: "Solidus", label: "Solidus" },
  { value: "Obol", label: "Obol" },
  { value: "Prutah", label: "Prutah" },
  { value: "Æ", label: "Æ" },
  { value: "Æ1", label: "Æ1" },
  { value: "Æ2", label: "Æ2" },
  { value: "Æ3", label: "Æ3" },
  { value: "Æ4", label: "Æ4" },
  { value: "Decanummium", label: "Decanummium" },
  { value: "Centenionalis", label: "Centenionalis" },
  { value: "Miliarense", label: "Miliarense" },
  { value: "Maiorina", label: "Maiorina" },
  { value: "Quinarius", label: "Quinarius" },
  { value: "Quadrans", label: "Quadrans" },
  { value: "Other", label: "Other" },
]

export const civilizationOptions = [
  { value: "Roman Imperial", label: "Roman Imperial" },
  { value: "Roman Republic", label: "Roman Republic" },
  { value: "Roman Provincial", label: "Roman Provincial" },
  { value: "Byzantine", label: "Byzantine" },
  { value: "Ancient Greece", label: "Ancient Greece" },
  { value: "Carthage", label: "Carthage" },
  { value: "Judea", label: "Judea" },
  { value: "Persian", label: "Persian" },
  { value: "Parthian", label: "Parthian" },
  { value: "Sassanian", label: "Sassanian" },
  { value: "Palmyrene Empire", label: "Palmyrene Empire" },
  { value: "Gallic Empire", label: "Gallic Empire" },
]
