export const mockCoins = [
  {
    id: 5,
    created_at: "2025-09-29T12:02:17.797917+00:00",
    nickname: "Faustina II",
    authority: "Augusta",
    denomination: "Denarius",
    civ: "Roman Imperial",
    reign_start: 147,
    reign_end: 175,
    diameter: 17,
    mass: 3.4,
    die_axis: "",
    metal: "Silver",
    silver_content: null,
    mint: "Rome",
    mint_year_earliest: 161,
    mint_year_latest: 176,
    legend_o: "FAVSTINA AVGVSTA",
    desc_o:
      "Draped bust right, bare-headed, hair waved and fastened in a bun on back of head.",
    legend_r: "VENVS",
    desc_r:
      "Venus, draped, standing left, holding dove in right hand and sceptre in left hand.",
    reference: "RIC III Marcus Aurelius 730",
    reference_link: null,
    purchase_type: "retail",
    purchase_date: "2025-07-14",
    price_aud: 149,
    price_shipping_aud: 1.57,
    purchase_vendor: "Imperial Numismatics",
    purchase_link:
      "https://imperialnumismatics.com.au/product/ancient-roman-imperial-silver-coin-faustina-junior-ar-denarius-ar-161-176-venus/",
    auction_name: "",
    auction_lot: null,
    provenance: "",
    notes: "",
    notes_history: "",
    user_id: "9f3e0c96-82f5-403b-a279-190e7f61d27d",
    vendor_grading_notes: "",
    image_link_o: "20250714__faustina-ii-denarius__o__src-imperial-numismatics",
    image_link_r: "20250714__faustina-ii-denarius__r__src-imperial-numismatics",
    image_link_zoom_o: null,
    image_link_zoom_r: null,
    flavour_text:
      "Venus was the divine ancestor of the Julian dynasty through her son Aeneas. This reverse type emphasizes the goddess's connection to imperial legitimacy and divine favor.",
    image_rotation: null,
    antiquities_register: "",
  },
  {
    id: 1,
    created_at: "2025-09-26T00:11:29.197019+00:00",
    nickname: "Faustina II (Diana)",
    authority: "Augusta",
    denomination: "Sestertius",
    civ: "Roman Imperial",
    reign_start: 161,
    reign_end: 176,
    diameter: 32.8,
    mass: 26,
    die_axis: "11h",
    metal: "Bronze",
    silver_content: null,
    mint: "Rome",
    mint_year_earliest: 161,
    mint_year_latest: 176,
    legend_o: "FAVSTINA AVGVSTA",
    desc_o:
      "Bust of Faustina the Younger, draped, hair elaborately waved in nearly vertical lines and fastened in a low chignon at back of head, down cheek, curls, right.",
    legend_r: "DIANA LVCIF S C",
    desc_r:
      "Diana, draped, standing front, head left, holding transverse lighted torch in both hands.",
    reference: "RIC III 1628 (Marcus Aurelius)",
    reference_link: null,
    purchase_type: "retail",
    purchase_date: "2025-08-20",
    price_aud: 129,
    price_shipping_aud: 3.67,
    purchase_vendor: "Imperial Numismatics",
    purchase_link:
      "https://imperialnumismatics.com.au/product/ancient-roman-imperial-coin-faustina-ii-ad-161-176-ae-sestertius-rome-mint-diana/",
    auction_name: null,
    auction_lot: null,
    provenance: "ex dummy data collection",
    notes: null,
    notes_history:
      "Daughter of Antoninus Pius, wife of Marcus Aurelius. at least 13 children, up to 6 stillborn. At least 4 reached adulthood (Lucilla, Commodus, Fadilla, Cornificia). Diana goddess of the moon, the hunt and women in childbirth.",
    user_id: "9f3e0c96-82f5-403b-a279-190e7f61d27d",
    vendor_grading_notes: null,
    image_link_o:
      "20250820__faustina-ii-sestertius__o__src-imperial-numismatics",
    image_link_r:
      "20250820__faustina-ii-sestertius__r__src-imperial-numismatics",
    image_link_zoom_o: null,
    image_link_zoom_r: null,
    flavour_text:
      "Daughter of Antoninus Pius, wife of Marcus Aurelius. at least 13 children, up to 6 stillborn. At least 4 reached adulthood (Lucilla, Commodus, Fadilla, Cornificia). Diana goddess of the moon, the hunt and women in childbirth.",
    image_rotation: null,
    antiquities_register: null,
  },
  {
    id: 7,
    created_at: "2025-09-29T21:57:14.090315+00:00",
    nickname: "Julia Mamea",
    authority: "Augusta",
    denomination: "Denarius",
    civ: "Roman Imperial",
    reign_start: 222,
    reign_end: 235,
    diameter: 20,
    mass: 3.27,
    die_axis: "",
    metal: "Silver",
    silver_content: null,
    mint: "Rome",
    mint_year_earliest: 225,
    mint_year_latest: 235,
    legend_o: "IVLIA MAMAEA AVG",
    desc_o: "Diademed, draped bust, right.",
    legend_r: "FELICITAS PVBLICA",
    desc_r:
      "Felicitas, draped, seated left, holding caduceus in right hand and cornucopiae in left hand.",
    reference: "RIC IV Severus Alexander 338",
    reference_link: null,
    purchase_type: "retail",
    purchase_date: "2025-07-18",
    price_aud: 139,
    price_shipping_aud: 2.75,
    purchase_vendor: "Imperial Numismatics",
    purchase_link:
      "https://imperialnumismatics.com.au/product/ancient-roman-imperial-silver-coin-julia-mamaea-ar-denarius-ar-225-235-felicitas/",
    auction_name: "",
    auction_lot: null,
    provenance: "",
    notes: "",
    notes_history: "",
    user_id: "9f3e0c96-82f5-403b-a279-190e7f61d27d",
    vendor_grading_notes: "",
    image_link_o: "20250718__julia-mamea-denarius__o__src-imperial-numismatics",
    image_link_r: "20250718__julia-mamea-denarius__r__src-imperial-numismatics",
    image_link_zoom_o: null,
    image_link_zoom_r: null,
    flavour_text: "",
    image_rotation: null,
    antiquities_register: "",
  },
];
