export const mockCoins = [
  {
    id: 61,
    created_at: "2025-10-06T04:17:05.712435+00:00",
    nickname: "Q. Fabius Labeo",
    authority: "Republican",
    denomination: "Denarius",
    civ: "Roman Republic",
    civ_specific: "",
    reign_start: -124,
    reign_end: -124,
    diameter: 18.5,
    mass: 3.77,
    die_axis: "3h",
    metal: "Silver",
    silver_content: "96-98",
    mint: "Rome",
    mint_year_earliest: -124,
    mint_year_latest: -124,
    legend_o: "X ROMA LABEO",
    legend_o_expanded: " X ROMA LABEO (M. Atilius)",
    legend_o_translation: "issued by Labeo (moneyer) on behalf of Rome",
    desc_o:
      "Helmeted head of Roma to right; X (mark of value) below chin, ROMA downwards behind, LABEO upwards before.",
    legend_r: "Q•FABI",
    legend_r_expanded: "Q(uintus) Fabi(us)",
    legend_r_translation: "",
    desc_r:
      "Jupiter driving galloping quadriga right, holding reins and sceptre and throwing thunderbolt; prow of galley below, Q•FABI in exergue.",
    reference: "Crawford-273/1; RSC Fabia-1",
    reference_link: null,
    purchase_type: "auction",
    purchase_date: "2025-09-11",
    price_aud: 138.29,
    price_shipping_aud: 4,
    purchase_vendor: "The Coin Cabinet",
    purchase_link: "https://www.numisbids.com/sale/9672/lot/145",
    auction_name: "Ancients 26",
    auction_lot: 145,
    provenance: "",
    notes: "",
    notes_history: "",
    user_id: "9f3e0c96-82f5-403b-a279-190e7f61d27d",
    vendor_grading_notes: "About Good Very Fine.",
    image_link_o: "20250911__q-fabius-labeo-denarius__o__src-the-coin-cabinet",
    image_link_r: "20250911__q-fabius-labeo-denarius__r__src-the-coin-cabinet",
    image_link_sketch_o:
      "20250911__q-fabius-labeo-denarius__o__src-the-coin-cabinet",
    image_link_sketch_r:
      "20250911__q-fabius-labeo-denarius__r__src-the-coin-cabinet",
    image_link_altlight_o:
      "20250911__q-fabius-labeo-denarius__o__src-the-coin-cabinet",
    image_link_altlight_r:
      "20250911__q-fabius-labeo-denarius__r__src-the-coin-cabinet",
    image_link_zoom_o: null,
    image_link_zoom_r: null,
    flavour_text:
      "X is the denomination - worth 10 bronze Asses. Marcus Atilius Labeo was a moneyer at the mint - outside this role we don't know much about him. He wa of the gens Atilia. This was a plebeian family (perhaps more like a 'clan') that tracked it's ancestry and had sacra gentilicia (it's own gods, rites and rituals).",
    deity_id: ["1"], // Jupiter
    bpRoute: ["/articles/republic-coins", "/articles/roman-moneyers"],
    image_rotation: null,
    antiquities_register: "",
    ex_collection: false,
    sets: null,
  },
  {
    id: 5,
    created_at: "2025-09-29T12:02:17.797917+00:00",
    nickname: "Faustina II",
    authority: "Augusta",
    denomination: "Denarius",
    civ: "Roman Imperial",
    civ_specific: null,
    reign_start: 147,
    reign_end: 175,
    diameter: 17,
    mass: 3.4,
    die_axis: "",
    metal: "Silver",
    silver_content: null,
    mint: "Rome",
    mint_year_earliest: 161,
    mint_year_latest: 176,
    legend_o: "FAVSTINA AVGVSTA",
    desc_o:
      "Draped bust right, bare-headed, hair waved and fastened in a bun on back of head.",
    legend_r: "VENVS",
    desc_r:
      "Venus, draped, standing left, holding dove in right hand and sceptre in left hand.",
    reference: "RIC III Marcus Aurelius 730",
    reference_link: null,
    purchase_type: "retail",
    purchase_date: "2025-07-14",
    price_aud: 149,
    price_shipping_aud: 1.57,
    purchase_vendor: "Imperial Numismatics",
    purchase_link:
      "https://imperialnumismatics.com.au/product/ancient-roman-imperial-silver-coin-faustina-junior-ar-denarius-ar-161-176-venus/",
    auction_name: "",
    auction_lot: null,
    provenance: "",
    notes: "",
    notes_history: "",
    user_id: "9f3e0c96-82f5-403b-a279-190e7f61d27d",
    vendor_grading_notes: "",
    image_link_o: "20250714__faustina-ii-denarius__o__src-imperial-numismatics",
    image_link_r: "20250714__faustina-ii-denarius__r__src-imperial-numismatics",
    image_link_sketch_o:
      "20250714__faustina-ii-denarius__o__src-imperial-numismatics",
    image_link_sketch_r:
      "20250714__faustina-ii-denarius__r__src-imperial-numismatics",
    image_link_altlight_o:
      "20250714__faustina-ii-denarius__o__src-imperial-numismatics",
    image_link_altlight_r:
      "20250714__faustina-ii-denarius__r__src-imperial-numismatics",
    image_link_zoom_o: null,
    image_link_zoom_r: null,
    flavour_text:
      "Venus was the divine ancestor of the Julian dynasty through her son Aeneas. This reverse type emphasizes the goddess's connection to imperial legitimacy and divine favor.",
    deity_id: ["2"], // Venus
    bpRoute: ["/articles/imperial-women", "/articles/faustina-ii"],
    image_rotation: null,
    antiquities_register: "",
  },
  {
    id: 1,
    created_at: "2025-09-26T00:11:29.197019+00:00",
    nickname: "Faustina II (Diana)",
    authority: "Augusta",
    denomination: "Sestertius",
    civ: "Roman Imperial",
    civ_specific: null,
    reign_start: 161,
    reign_end: 176,
    diameter: 32.8,
    mass: 26,
    die_axis: "11h",
    metal: "Bronze",
    silver_content: null,
    mint: "Rome",
    mint_year_earliest: 161,
    mint_year_latest: 176,
    legend_o: "FAVSTINA AVGVSTA",
    desc_o:
      "Bust of Faustina the Younger, draped, hair elaborately waved in nearly vertical lines and fastened in a low chignon at back of head, down cheek, curls, right.",
    legend_r: "DIANA LVCIF S C",
    desc_r:
      "Diana, draped, standing front, head left, holding transverse lighted torch in both hands.",
    reference: "RIC III 1628 (Marcus Aurelius)",
    reference_link: null,
    purchase_type: "retail",
    purchase_date: "2025-08-20",
    price_aud: 129,
    price_shipping_aud: 3.67,
    purchase_vendor: "Imperial Numismatics",
    purchase_link:
      "https://imperialnumismatics.com.au/product/ancient-roman-imperial-coin-faustina-ii-ad-161-176-ae-sestertius-rome-mint-diana/",
    auction_name: null,
    auction_lot: null,
    provenance: "ex dummy data collection",
    notes: null,
    notes_history:
      "Daughter of Antoninus Pius, wife of Marcus Aurelius. at least 13 children, up to 6 stillborn. At least 4 reached adulthood (Lucilla, Commodus, Fadilla, Cornificia). Diana goddess of the moon, the hunt and women in childbirth.",
    user_id: "9f3e0c96-82f5-403b-a279-190e7f61d27d",
    vendor_grading_notes: null,
    image_link_o:
      "20250820__faustina-ii-sestertius__o__src-imperial-numismatics",
    image_link_r:
      "20250820__faustina-ii-sestertius__r__src-imperial-numismatics",
    image_link_sketch_o:
      "20250820__faustina-ii-sestertius__o__src-imperial-numismatics",
    image_link_sketch_r:
      "20250820__faustina-ii-sestertius__r__src-imperial-numismatics",
    image_link_altlight_o:
      "20250820__faustina-ii-sestertius__o__src-imperial-numismatics",
    image_link_altlight_r:
      "20250820__faustina-ii-sestertius__r__src-imperial-numismatics",
    image_link_zoom_o: null,
    image_link_zoom_r: null,
    flavour_text:
      "Daughter of Antoninus Pius, wife of Marcus Aurelius. at least 13 children, up to 6 stillborn. At least 4 reached adulthood (Lucilla, Commodus, Fadilla, Cornificia). Diana goddess of the moon, the hunt and women in childbirth.",
    deity_id: ["3"], // Diana
    bpRoute: ["/articles/imperial-women", "/articles/marcus-aurelius"],
    image_rotation: null,
    antiquities_register: null,
  },
  {
    id: 7,
    created_at: "2025-09-29T21:57:14.090315+00:00",
    nickname: "Julia Mamea",
    authority: "Augusta",
    denomination: "Denarius",
    civ: "Roman Imperial",
    civ_specific: null,
    reign_start: 222,
    reign_end: 235,
    diameter: 20,
    mass: 3.27,
    die_axis: "",
    metal: "Silver",
    silver_content: null,
    mint: "Rome",
    mint_year_earliest: 225,
    mint_year_latest: 235,
    legend_o: "IVLIA MAMAEA AVG",
    desc_o: "Diademed, draped bust, right.",
    legend_r: "FELICITAS PVBLICA",
    desc_r:
      "Felicitas, draped, seated left, holding caduceus in right hand and cornucopiae in left hand.",
    reference: "RIC IV Severus Alexander 338",
    reference_link: null,
    purchase_type: "retail",
    purchase_date: "2025-07-18",
    price_aud: 139,
    price_shipping_aud: 2.75,
    purchase_vendor: "Imperial Numismatics",
    purchase_link:
      "https://imperialnumismatics.com.au/product/ancient-roman-imperial-silver-coin-julia-mamaea-ar-denarius-ar-225-235-felicitas/",
    auction_name: "",
    auction_lot: null,
    provenance: "",
    notes: "",
    notes_history: "",
    user_id: "9f3e0c96-82f5-403b-a279-190e7f61d27d",
    vendor_grading_notes: "",
    image_link_o: "20250718__julia-mamea-denarius__o__src-imperial-numismatics",
    image_link_r: "20250718__julia-mamea-denarius__r__src-imperial-numismatics",
    image_link_sketch_o: null,
    image_link_sketch_r: null,
    image_link_altlight_o: null,
    image_link_altlight_r: null,
    image_link_zoom_o: null,
    image_link_zoom_r: null,
    flavour_text: "",
    deity_id: null,
    bpRoute: null,
    image_rotation: null,
    antiquities_register: "",
  },
]

// Mock coin specifically for CoinSketchCompare component
export const mockCoinWithSketches = {
  imageLinkO: "20250911__q-fabius-labeo-denarius__o__src-the-coin-cabinet",
  imageLinkSketchO:
    "20250911__q-fabius-labeo-denarius__o__src-the-coin-cabinet",
  imageLinkR: "20250911__q-fabius-labeo-denarius__r__src-the-coin-cabinet",
  imageLinkSketchR:
    "20250911__q-fabius-labeo-denarius__o__src-the-coin-cabinet",
  legendExpandedO: " X ROMA LABEO (M. Atilius)",
  legendTranslationO: "issued by Labeo (moneyer) on behalf of Rome",
  legendExpandedR:
    "Q(uintus) Fabi(us) Q(uintus) Fabi(us) Q(uintus) Fabi(us) Q(uintus) Fabi(us) Q(uintus) Fabi(us)",
  legendTranslationR:
    "a mock translation of considerable length to test wrapping and overflow behavior etc etc etc. a mock translation of considerable length to test wrapping and overflow behavior etc etc etc.",
}

export const mockCoinWithoutSketches = {
  imageLinkO: "20250911__q-fabius-labeo-denarius__o__src-the-coin-cabinet",
  imageLinkSketchO: null,
  imageLinkR: "20250911__q-fabius-labeo-denarius__r__src-the-coin-cabinet",
  imageLinkSketchR: null,
  legendExpandedO: " X ROMA LABEO (M. Atilius)",
  legendTranslationO: "issued by Labeo (moneyer) on behalf of Rome",
  legendExpandedR: "Q(uintus) Fabi(us)",
  legendTranslationR: "",
}

export const threeMockCoins = [
  {
    id: 66,
    nickname: "Faustina II",
    civ: "Roman Imperial",
    denomination: "Sestertius",
    mintYearEarliest: 161,
    mintYearLatest: 176,
    obverseImageId:
      "20250820__faustina-ii-sestertius__o__src-imperial-numismatics",
    reverseImageId:
      "20250820__faustina-ii-sestertius__r__src-imperial-numismatics",
    diameter: 32.8,
  },
  {
    id: 74,
    nickname: "Marcus Aurelius",
    civ: "Roman Imperial",
    denomination: "Denarius",
    mintYearEarliest: 220,
    mintYearLatest: 222,
    obverseImageId: "20251002__elagabalus-denarius__o__src-the-coin-cabinet",
    reverseImageId: "20251002__elagabalus-denarius__r__src-the-coin-cabinet",
    diameter: 19,
  },
  {
    id: 95,
    nickname: "Constantius I Chlorus (Rauceby Hoard)",
    civ: "Roman Imperial",
    denomination: "Follis",
    mintYearEarliest: 295,
    mintYearLatest: 295,
    obverseImageId:
      "20250904__constantius-i-chlorus-rauceby-hoard-follis__o__src-noonans-mayfair",
    reverseImageId:
      "20250904__constantius-i-chlorus-rauceby-hoard-follis__r__src-noonans-mayfair",
    diameter: 29.2,
  },
]
