name: Weekly Database Backup

on:
  schedule:
    # Run weekly on Wednesdays at 2 AM UTC
    - cron: "0 2 * * 3"
  workflow_dispatch: # Allow manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Create database backup
        run: pnpm db:backup
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: database-backup-${{ github.run_number }}
          path: backups/
          retention-days: 30

      - name: Commit backup to repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add backups/
          git commit -m "Weekly automated database backup $(date +%Y-%m-%d)" || exit 0
          git push
